---
# handlers file for set-hostkeys
- name: restart ssh service when key changed if set_hostkeys_restart_service set to true
  service:
    name: sshd
    state: restarted
  when: set_hostkeys_restart_service

- name: delete known_hosts entry on Ansible controller
  ansible.builtin.command:
    cmd: ssh-keygen -R "{{ ansible_host }}"
  delegate_to: localhost

- name: add new ssh key to known_hosts
  ansible.builtin.command:
    cmd: ssh -o StrictHostKeyChecking=accept-new -o BatchMode=yes {{ ansible_user }}@{{ ansible_host }} exit
  delegate_to: localhost
